spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_microservices
    username: root
    password: akriti
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

server:
  port: 8082

